### PR TITLE
Done some tweaks on frontend

### PR DESCRIPTION
**Pull request by gajendrahitz**
Added the top nav bar hover+transition effect
Added the quick links hover+transition effect
Added blur effect on main-card(Junio-Dev one) and also added a hover effect
Added pointer as cursor on search icon and submit button
Added some amazing effects on find us on section
Added a cursor pointer on Courses heading and a href to it to go to courses when user clicks on it.
Added doubly underlines on course names
Added some on hover shadow on cards
Added a on hover mechanism on submit button

### CODE REVIEW

**Comment by JuniorDevTun** [comment]
Hey there 👋
Thanks for contributing to the project 🙏
However most of the changes you've made do not align with the overall theme of the site.

✅ Keep the hover effect on the cards (courses)
❌ The box-shadow on the main card
❌ The hover effect on the links
❌ The hover effect on the social media section

👉 Please raise an issue before making changes to avoid wasting your time on non necessary features

🤝 Will be waiting for your changes

**Comment by gajendrahitz** [comment]
Sorry For not raising an issue before making a pull request @JuniorDevTun  . Actually this was my first contribution at github so not much familiar with it's flow . Can you clarify If I need to add "✅ Keep the hover effect on the cards (courses)" to the front-end cause the PR was closed.

**Comment by AymKh** [comment]
Heu there 👋
no worries
if you want to make your first contribution, you can take a look at issue #8 
make a comment there asking to be assigned that issue, and we will go from there

**Comment by gajendrahitz** [comment]
Okk Thanks...

**Pull request closed without merging**
